"""Sales content owned by the institutional site. No magazine imports."""
PRODUCTS = (
    {'slug':'basic','name':'Basic','price':40000,'image':'planbo_basic.png'},
    {'slug':'standard','name':'Standard','price':65000,'image':'plano_standard.png'},
    {'slug':'premium','name':'Premium','price':100000,'image':'plano_premium.png'},
)

CONTENT = {
'pt-BR': {
 'seo_title':'Chalés de madeira e tiny houses | Chalet to Go',
 'seo_description':'Conheça os chalés Basic, Standard e Premium da Chalet to Go. Pinus seco em estufa e tratado, opções para morar ou receber hóspedes. Peça sua proposta pelo WhatsApp.',
 'collection':'Chalés','material':'Madeira','warranty':'Garantias','language':'Idioma','home':'Início',
 'eyebrow':'Chalés de madeira • Tiny houses', 'hero':'Seu próximo endereço pode ser mais perto da natureza.',
 'lead':'Do seu refúgio particular a um espaço para receber hóspedes: escolha o chalé que combina com seu projeto e converse com quem vai ajudar a tirá-lo do papel.',
 'cta':'Quero meu chalé','plan_cta':'Quero uma proposta','whatsapp':'Fale pelo WhatsApp','details':'Conheça o modelo',
 'collection_title':'Três modelos. Um novo jeito de viver.',
 'collection_intro':'Compare as propostas e encontre o ponto de partida para sua casa, seu refúgio ou seu projeto de hospedagem.',
 'models':['Uma tiny house compacta e padronizada para começar seu projeto com o essencial.','Um chalé modular para a vida em família ou para receber hóspedes.','Um chalé de alto padrão, personalizado para o seu jeito de viver.'],
 'benefits':['Seu refúgio, na medida do essencial.','Mais possibilidades para morar e receber.','Um projeto com a sua personalidade.'],
 'material_title':'O cuidado começa na madeira.',
 'material_body':'Utilizamos pinus seco em estufa e tratado, com foco na qualidade e na resistência da madeira. A escolha entre madeira suíça e brasileira também define as condições de garantia do seu projeto.',
 'warranty_title':'Escolha a madeira. Entenda a proteção.',
 'swiss_title':'Madeira suíça','swiss_term':'Até 20 anos','swiss_body':'Cobertura opcional da Generali para o chalé construído com madeira suíça, mediante valor adicional. O prazo de até 20 anos depende das condições contratadas; não é uma cobertura automática incluída no preço.',
 'brazil_title':'Madeira brasileira','brazil_term':'6 meses','brazil_body':'A garantia informada para madeira brasileira é de 6 meses. Consulte o escopo, as condições e as responsabilidades previstas na proposta.',
 'warranty_note':'Peça pelo WhatsApp as condições da cobertura, a disponibilidade no país de instalação e o orçamento com a opção de madeira desejada.',
 'gallery_title':'Imagine a vida acontecendo aqui.','gallery_body':'Madeira, luz e espaços para o cotidiano. Inspire-se e converse com nossa equipe sobre o seu projeto.',
 'image_note':'Imagens ilustrativas. Configuração, acabamentos e itens incluídos são definidos na proposta.',
 'price_note':'Valor de referência em CHF. Confirme os itens incluídos e as condições comerciais na proposta; a cobertura opcional da Generali tem custo adicional.',
 'closing_title':'Seu chalé começa com uma conversa.','closing_body':'Conte onde você quer instalar, como pretende usar e qual modelo chamou sua atenção. Vamos conversar sobre as possibilidades.',
 'message':'Olá! Quero saber mais sobre os chalés da Chalet to Go.',
 'plan_message':'Olá! Tenho interesse no chalé {model} da Chalet to Go. Gostaria de uma proposta e das condições de garantia.',
 'back':'Ver todos os chalés','product_title':'Chalé {model} de madeira | Chalet to Go','gallery_alt':'Ambiente interno de chalé de madeira, imagem ilustrativa',
},
'en': {
 'seo_title':'Timber chalets and tiny houses | Chalet to Go','seo_description':'Explore Basic, Standard and Premium timber chalets. Kiln-dried, treated pine for homes and guest accommodation. Request your proposal on WhatsApp.',
 'collection':'Chalets','material':'Timber','warranty':'Warranties','language':'Language','home':'Home',
 'eyebrow':'Timber chalets • Tiny houses','hero':'Your next address could be closer to nature.','lead':'From a private retreat to a place for guests: choose a chalet that fits your project and talk to the team about bringing it to life.',
 'cta':'Find my chalet','plan_cta':'Request a proposal','whatsapp':'Talk on WhatsApp','details':'Explore the model',
 'collection_title':'Three models. A new way to live.','collection_intro':'Compare the options and find a starting point for your home, retreat or accommodation project.',
 'models':['A compact, standardised tiny house to start your project with the essentials.','A modular chalet for family life or welcoming guests.','A high-end chalet tailored to your way of living.'],
 'benefits':['Your retreat, with the essentials.','More possibilities for living and hosting.','A project with your personality.'],
 'material_title':'Care starts with the timber.','material_body':'We use kiln-dried and treated pine, with a focus on timber quality and resistance. Choosing Swiss or Brazilian timber also determines the warranty conditions for your project.',
 'warranty_title':'Choose the timber. Understand the protection.','swiss_title':'Swiss timber','swiss_term':'Up to 20 years','swiss_body':'Optional Generali coverage for a chalet built with Swiss timber, at an additional cost. The period of up to 20 years depends on the contracted terms; it is not automatically included in the price.',
 'brazil_title':'Brazilian timber','brazil_term':'6 months','brazil_body':'The stated warranty for Brazilian timber is 6 months. Ask about the scope, terms and responsibilities in the proposal.',
 'warranty_note':'Ask on WhatsApp about coverage terms, availability in the installation country and a quotation with your preferred timber option.',
 'gallery_title':'Picture life unfolding here.','gallery_body':'Timber, light and spaces for everyday life. Find inspiration and discuss your project with our team.',
 'image_note':'Illustrative images. Configuration, finishes and included items are defined in the proposal.','price_note':'Reference price in CHF. Confirm included items and commercial terms in your proposal; optional Generali coverage costs extra.',
 'closing_title':'Your chalet starts with a conversation.','closing_body':'Tell us where you want to install it, how you plan to use it and which model caught your attention. Let’s explore the possibilities.',
 'message':'Hello! I would like to learn more about Chalet to Go chalets.','plan_message':'Hello! I am interested in the Chalet to Go {model} chalet. I would like a proposal and warranty terms.',
 'back':'View all chalets','product_title':'{model} timber chalet | Chalet to Go','gallery_alt':'Timber chalet interior, illustrative image',
},
'fr': {
 'seo_title':'Chalets en bois et tiny houses | Chalet to Go','seo_description':'Découvrez les chalets Basic, Standard et Premium. Pin séché en étuve et traité pour habiter ou accueillir des hôtes. Demandez une offre sur WhatsApp.',
 'collection':'Chalets','material':'Bois','warranty':'Garanties','language':'Langue','home':'Accueil',
 'eyebrow':'Chalets en bois • Tiny houses','hero':'Votre prochaine adresse pourrait être plus près de la nature.','lead':'D’un refuge privé à un lieu pour accueillir des hôtes : choisissez le chalet adapté à votre projet et discutons de sa réalisation.',
 'cta':'Trouver mon chalet','plan_cta':'Demander une offre','whatsapp':'Parlons sur WhatsApp','details':'Découvrir le modèle',
 'collection_title':'Trois modèles. Une nouvelle façon de vivre.','collection_intro':'Comparez les propositions pour votre maison, votre refuge ou votre projet d’hébergement.',
 'models':['Une tiny house compacte et standardisée pour commencer avec l’essentiel.','Un chalet modulaire pour la famille ou l’accueil de visiteurs.','Un chalet haut de gamme adapté à votre façon de vivre.'],
 'benefits':['Votre refuge, avec l’essentiel.','Plus de possibilités pour habiter et recevoir.','Un projet à votre image.'],
 'material_title':'Le soin commence avec le bois.','material_body':'Nous utilisons du pin séché en étuve et traité, en privilégiant la qualité et la résistance du bois. Le choix entre bois suisse et brésilien détermine aussi les conditions de garantie.',
 'warranty_title':'Choisir le bois. Comprendre la protection.','swiss_title':'Bois suisse','swiss_term':'Jusqu’à 20 ans','swiss_body':'Couverture Generali facultative pour le chalet construit en bois suisse, moyennant un supplément. La durée pouvant atteindre 20 ans dépend des conditions contractuelles ; elle n’est pas automatiquement comprise dans le prix.',
 'brazil_title':'Bois brésilien','brazil_term':'6 mois','brazil_body':'La garantie annoncée pour le bois brésilien est de 6 mois. Consultez le périmètre, les conditions et les responsabilités dans l’offre.',
 'warranty_note':'Demandez sur WhatsApp les conditions de couverture, la disponibilité dans le pays d’installation et une offre avec le bois souhaité.',
 'gallery_title':'Imaginez la vie ici.','gallery_body':'Bois, lumière et espaces du quotidien. Inspirez-vous et échangez avec notre équipe.',
 'image_note':'Images illustratives. Configuration, finitions et éléments inclus sont définis dans l’offre.','price_note':'Prix de référence en CHF. Confirmez les éléments inclus et les conditions commerciales ; la couverture Generali facultative entraîne un supplément.',
 'closing_title':'Votre chalet commence par une conversation.','closing_body':'Dites-nous où vous souhaitez l’installer, son usage et le modèle qui vous intéresse. Explorons les possibilités.',
 'message':'Bonjour ! Je souhaite en savoir plus sur les chalets Chalet to Go.','plan_message':'Bonjour ! Le chalet {model} de Chalet to Go m’intéresse. Je souhaite une offre et les conditions de garantie.',
 'back':'Voir tous les chalets','product_title':'Chalet {model} en bois | Chalet to Go','gallery_alt':'Intérieur de chalet en bois, image illustrative',
},
'de': {
 'seo_title':'Holzchalets und Tiny Houses | Chalet to Go','seo_description':'Entdecken Sie Basic, Standard und Premium: Chalets aus kammergetrockneter, behandelter Kiefer zum Wohnen und Beherbergen. Angebot per WhatsApp anfragen.',
 'collection':'Chalets','material':'Holz','warranty':'Garantien','language':'Sprache','home':'Startseite',
 'eyebrow':'Holzchalets • Tiny Houses','hero':'Ihr nächstes Zuhause könnte näher an der Natur liegen.','lead':'Vom privaten Rückzugsort bis zur Gästeunterkunft: Finden Sie das passende Chalet und sprechen Sie mit uns über Ihr Vorhaben.',
 'cta':'Mein Chalet finden','plan_cta':'Angebot anfragen','whatsapp':'Kontakt per WhatsApp','details':'Modell entdecken',
 'collection_title':'Drei Modelle. Eine neue Art zu leben.','collection_intro':'Vergleichen Sie die Möglichkeiten für Ihr Zuhause, Ihren Rückzugsort oder Ihr Beherbergungsprojekt.',
 'models':['Ein kompaktes, standardisiertes Tiny House mit dem Wesentlichen.','Ein modulares Chalet für Familien oder Gäste.','Ein hochwertiges Chalet, auf Ihre Lebensweise abgestimmt.'],
 'benefits':['Ihr Rückzugsort mit dem Wesentlichen.','Mehr Möglichkeiten zum Wohnen und Empfangen.','Ein Projekt mit Ihrer Persönlichkeit.'],
 'material_title':'Sorgfalt beginnt beim Holz.','material_body':'Wir verwenden kammergetrocknetes und behandeltes Kiefernholz mit Fokus auf Qualität und Widerstandsfähigkeit. Die Wahl zwischen Schweizer und brasilianischem Holz bestimmt auch die Garantiebedingungen.',
 'warranty_title':'Holz wählen. Den Schutz verstehen.','swiss_title':'Schweizer Holz','swiss_term':'Bis zu 20 Jahre','swiss_body':'Optionale Generali-Deckung für das Chalet aus Schweizer Holz gegen Aufpreis. Die Laufzeit von bis zu 20 Jahren hängt von den Vertragsbedingungen ab und ist nicht automatisch im Preis enthalten.',
 'brazil_title':'Brasilianisches Holz','brazil_term':'6 Monate','brazil_body':'Die angegebene Garantie für brasilianisches Holz beträgt 6 Monate. Umfang, Bedingungen und Verantwortlichkeiten sind im Angebot zu klären.',
 'warranty_note':'Fragen Sie per WhatsApp nach Deckungsbedingungen, Verfügbarkeit im Aufstellungsland und einem Angebot mit Ihrer gewünschten Holzoption.',
 'gallery_title':'Stellen Sie sich das Leben hier vor.','gallery_body':'Holz, Licht und Räume für den Alltag. Lassen Sie sich inspirieren und sprechen Sie mit unserem Team.',
 'image_note':'Illustrative Bilder. Konfiguration, Ausführungen und enthaltene Leistungen werden im Angebot festgelegt.','price_note':'Referenzpreis in CHF. Enthaltene Leistungen und Konditionen im Angebot bestätigen lassen; die optionale Generali-Deckung kostet zusätzlich.',
 'closing_title':'Ihr Chalet beginnt mit einem Gespräch.','closing_body':'Wo soll es stehen, wie möchten Sie es nutzen und welches Modell interessiert Sie? Gemeinsam erkunden wir die Möglichkeiten.',
 'message':'Hallo! Ich möchte mehr über die Chalets von Chalet to Go erfahren.','plan_message':'Hallo! Ich interessiere mich für das Chalet {model} von Chalet to Go und wünsche ein Angebot sowie die Garantiebedingungen.',
 'back':'Alle Chalets ansehen','product_title':'Holzchalet {model} | Chalet to Go','gallery_alt':'Innenraum eines Holzchalets, illustratives Bild',
},
'it': {
 'seo_title':'Chalet in legno e tiny house | Chalet to Go','seo_description':'Scopri Basic, Standard e Premium: chalet in pino essiccato in forno e trattato per abitare o accogliere ospiti. Richiedi una proposta su WhatsApp.',
 'collection':'Chalet','material':'Legno','warranty':'Garanzie','language':'Lingua','home':'Home',
 'eyebrow':'Chalet in legno • Tiny house','hero':'La tua prossima casa può essere più vicina alla natura.','lead':'Dal rifugio privato all’alloggio per ospiti: scegli lo chalet adatto al tuo progetto e parliamo di come realizzarlo.',
 'cta':'Trova il mio chalet','plan_cta':'Richiedi una proposta','whatsapp':'Parliamo su WhatsApp','details':'Scopri il modello',
 'collection_title':'Tre modelli. Un nuovo modo di vivere.','collection_intro':'Confronta le proposte per la tua casa, il tuo rifugio o il tuo progetto ricettivo.',
 'models':['Una tiny house compatta e standardizzata per iniziare con l’essenziale.','Uno chalet modulare per la famiglia o per accogliere ospiti.','Uno chalet di alta gamma personalizzato per il tuo modo di vivere.'],
 'benefits':['Il tuo rifugio con l’essenziale.','Più possibilità per abitare e accogliere.','Un progetto con la tua personalità.'],
 'material_title':'La cura inizia dal legno.','material_body':'Utilizziamo pino essiccato in forno e trattato, con attenzione alla qualità e alla resistenza. La scelta fra legno svizzero e brasiliano determina anche le condizioni di garanzia.',
 'warranty_title':'Scegli il legno. Comprendi la protezione.','swiss_title':'Legno svizzero','swiss_term':'Fino a 20 anni','swiss_body':'Copertura Generali facoltativa per lo chalet costruito con legno svizzero, a costo aggiuntivo. La durata fino a 20 anni dipende dalle condizioni contrattuali e non è automaticamente inclusa nel prezzo.',
 'brazil_title':'Legno brasiliano','brazil_term':'6 mesi','brazil_body':'La garanzia indicata per il legno brasiliano è di 6 mesi. Consulta ambito, condizioni e responsabilità nella proposta.',
 'warranty_note':'Chiedi su WhatsApp le condizioni della copertura, la disponibilità nel paese di installazione e un preventivo con il legno desiderato.',
 'gallery_title':'Immagina la vita qui.','gallery_body':'Legno, luce e spazi quotidiani. Lasciati ispirare e parla con il nostro team.',
 'image_note':'Immagini illustrative. Configurazione, finiture ed elementi inclusi sono definiti nella proposta.','price_note':'Prezzo di riferimento in CHF. Conferma elementi inclusi e condizioni commerciali; la copertura Generali facoltativa ha un costo aggiuntivo.',
 'closing_title':'Il tuo chalet inizia con una conversazione.','closing_body':'Raccontaci dove vuoi installarlo, come lo userai e quale modello ti interessa. Esploriamo le possibilità.',
 'message':'Ciao! Vorrei saperne di più sugli chalet di Chalet to Go.','plan_message':'Ciao! Mi interessa lo chalet {model} di Chalet to Go. Vorrei una proposta e le condizioni di garanzia.',
 'back':'Vedi tutti gli chalet','product_title':'Chalet {model} in legno | Chalet to Go','gallery_alt':'Interno di chalet in legno, immagine illustrativa',
},
'rm': {
 'seo_title':'Chalets da lain e tiny houses | Chalet to Go','seo_description':'Descuvra Basic, Standard e Premium: chalets da pin setgentà en furn e tractà per viver u retschaiver giasts. Dumonda in’offerta via WhatsApp.',
 'collection':'Chalets','material':'Lain','warranty':'Garanzias','language':'Lingua','home':'Pagina iniziala',
 'eyebrow':'Chalets da lain • Tiny houses','hero':'Tia proxima chasa po esser pli datiers da la natira.','lead':'Da tes refugi privat ad in lieu per giasts: tscherna il chalet adattà e discurra cun nus davart tes project.',
 'cta':'Chattar mes chalet','plan_cta':'Dumandar in’offerta','whatsapp':'Discurrer via WhatsApp','details':'Descuvrir il model',
 'collection_title':'Trais models. Ina nova moda da viver.','collection_intro':'Cumpareglia las propostas per tia chasa, tes refugi u tes project d’alloschament.',
 'models':['Ina tiny house compacta e standardisada cun l’essenzial.','In chalet modular per famiglias u giasts.','In chalet d’auta qualitad adattà a tia moda da viver.'],
 'benefits':['Tes refugi cun l’essenzial.','Pli bleras pussaivladads per viver e retschaiver.','In project cun tia persunalitad.'],
 'material_title':'Il quità cumenza cun il lain.','material_body':'Nus duvrain pin setgentà en furn e tractà, cun accent sin qualitad e resistenza. La tscherna tranter lain svizzer e brasilian determinescha er las cundiziuns da garanzia.',
 'warranty_title':'Tscherner il lain. Chapir la protecziun.','swiss_title':'Lain svizzer','swiss_term':'Fin a 20 onns','swiss_body':'Cuverta facultativa da Generali per il chalet construì cun lain svizzer, cunter custs supplementars. La durada fin a 20 onns dependa dal contract e n’è betg automaticamain inclusa en il pretsch.',
 'brazil_title':'Lain brasilian','brazil_term':'6 mais','brazil_body':'La garanzia inditgada per lain brasilian è da 6 mais. Dumonda davart l’extensiun, las cundiziuns e las responsabladads en l’offerta.',
 'warranty_note':'Dumonda via WhatsApp las cundiziuns da cuverta, la disponibladad en il pajais d’installaziun ed in’offerta cun il lain giavischà.',
 'gallery_title':'Imagina la vita qua.','gallery_body':'Lain, glisch e spazis per il mintgadi. Ta lascha inspirar e discurra cun nossa squadra.',
 'image_note':'Maletgs illustrativs. Configuraziun, finiziuns ed elements inclus vegnan definids en l’offerta.','price_note':'Pretsch da referenza en CHF. Conferma ils elements inclus e las cundiziuns; la cuverta facultativa da Generali custa supplementarmain.',
 'closing_title':'Tes chalet cumenza cun in discurs.','closing_body':'Ans di nua che ti vuls installar el, co che ti vuls duvrar el e tge model che t’interessa. Nus discurrin da las pussaivladads.',
 'message':'Bun di! Jau vuless savair dapli davart ils chalets da Chalet to Go.','plan_message':'Bun di! Jau m’interessesch per il chalet {model} da Chalet to Go e giavisch in’offerta e las cundiziuns da garanzia.',
 'back':'Vesair tut ils chalets','product_title':'Chalet {model} da lain | Chalet to Go','gallery_alt':'Intern d’in chalet da lain, maletg illustrativ',
}}
CONTENT['pt-PT'] = {**CONTENT['pt-BR'],
 'seo_description':'Conheça os chalés Basic, Standard e Premium. Pinho seco em estufa e tratado para habitação ou alojamento turístico. Peça uma proposta pelo WhatsApp.',
 'hero':'A sua próxima morada pode estar mais perto da natureza.',
 'lead':'Do seu refúgio privado a um espaço para receber hóspedes: escolha o chalé que combina com o seu projeto e fale connosco para o concretizar.',
 'material_body':'Utilizamos pinho seco em estufa e tratado, com foco na qualidade e resistência da madeira. A escolha entre madeira suíça e brasileira também define as condições de garantia do seu projeto.',
 'gallery_body':'Madeira, luz e espaços para o quotidiano. Inspire-se e fale com a nossa equipa sobre o seu projeto.',
 'closing_body':'Diga-nos onde pretende instalar o chalé, como o vai utilizar e qual o modelo que lhe interessa. Vamos explorar as possibilidades.',
 'message':'Olá! Gostaria de saber mais sobre os chalés da Chalet to Go.',
}

# Product narrative belongs exclusively to the institutional home.
HOME_STORIES = {
 'pt-BR': ('Um chalé para o que você quer viver.', [
 'A Chalet to Go desenvolve chalés de madeira para diferentes formas de morar e receber. A proposta começa com uma escolha simples: um espaço só seu, um refúgio para os fins de semana ou uma unidade para um projeto de hospedagem.',
 'Da tiny house compacta ao chalé modular familiar e ao projeto personalizado, cada modelo oferece um ponto de partida diferente. Antes de escolher, vale pensar em quem vai usar o espaço, na rotina que ele precisa acolher e no local de instalação.',
 'Nosso atendimento transforma essas ideias em uma proposta: conversamos sobre o modelo, a origem da madeira, os acabamentos e as condições de garantia. Assim, você conhece o que está contratando antes de dar o próximo passo.'], 'Galeria', 'Exterior de chalé de madeira, imagem ilustrativa', 'Ampliar imagem', 'Fechar imagem'),
 'pt-PT': ('Um chalé para a vida que imagina.', [
 'A Chalet to Go desenvolve chalés de madeira para diferentes formas de habitar e receber. O ponto de partida é a utilização que lhes pretende dar: uma casa, um refúgio para os fins de semana ou uma unidade de alojamento.',
 'Da tiny house compacta ao chalé modular familiar e ao projeto personalizado, cada modelo oferece uma proposta diferente. Pense em quem irá utilizar o espaço, nas necessidades do quotidiano e no local de instalação.',
 'A nossa equipa ajuda a transformar essas ideias numa proposta, considerando o modelo, a origem da madeira, os acabamentos e as condições de garantia. Conheça os elementos incluídos antes de avançar.'], 'Galeria', 'Exterior de chalé de madeira, imagem ilustrativa', 'Ampliar imagem', 'Fechar imagem'),
 'en': ('A chalet for the life you imagine.', [
 'Chalet to Go develops timber chalets for different ways of living and hosting. Start with the purpose: a home of your own, a weekend retreat or a unit for an accommodation project.',
 'From a compact tiny house to a family modular chalet or a customised project, each model offers a different starting point. Consider who will use the space, the everyday needs it should meet and the installation location.',
 'Our team helps turn those ideas into a proposal covering the model, timber origin, finishes and warranty terms. You can understand what is included before taking the next step.'], 'Gallery', 'Timber chalet exterior, illustrative image', 'Enlarge image', 'Close image'),
 'fr': ('Un chalet pour la vie que vous imaginez.', [
 'Chalet to Go développe des chalets en bois pour différentes façons de vivre et de recevoir. Le projet commence par votre usage : une habitation, un refuge pour les week-ends ou une unité pour un projet d’hébergement.',
 'De la tiny house compacte au chalet familial modulaire ou personnalisé, chaque modèle offre un point de départ différent. Pensez aux occupants, aux besoins du quotidien et au lieu d’installation.',
 'Notre équipe vous accompagne dans une proposition précisant le modèle, l’origine du bois, les finitions et les conditions de garantie. Vous découvrez les éléments inclus avant de poursuivre.'], 'Galerie', 'Extérieur de chalet en bois, image illustrative', 'Agrandir l’image', 'Fermer l’image'),
 'de': ('Ein Chalet für Ihr Leben.', [
 'Chalet to Go entwickelt Holzchalets für unterschiedliche Wohnformen und die Beherbergung von Gästen. Am Anfang steht Ihre Nutzung: ein eigenes Zuhause, ein Rückzugsort am Wochenende oder eine Einheit für ein Beherbergungsprojekt.',
 'Vom kompakten Tiny House über das modulare Familienchalet bis zum individuellen Projekt bietet jedes Modell einen anderen Ausgangspunkt. Entscheidend sind die künftigen Bewohner, ihr Alltag und der Aufstellungsort.',
 'Unser Team bespricht mit Ihnen Modell, Holzherkunft, Ausstattung und Garantiebedingungen. Daraus entsteht ein Angebot, dessen enthaltene Leistungen Sie vor dem nächsten Schritt kennenlernen.'], 'Galerie', 'Außenansicht eines Holzchalets, Beispielbild', 'Bild vergrößern', 'Bild schließen'),
 'it': ('Uno chalet per la vita che immagini.', [
 'Chalet to Go sviluppa chalet in legno per diversi modi di abitare e accogliere. Il progetto parte dall’utilizzo: una casa, un rifugio per il fine settimana o un’unità per un progetto ricettivo.',
 'Dalla tiny house compatta allo chalet familiare modulare o personalizzato, ogni modello offre un punto di partenza diverso. Considera chi utilizzerà lo spazio, le esigenze quotidiane e il luogo di installazione.',
 'Il nostro team traduce queste idee in una proposta che considera modello, origine del legno, finiture e condizioni di garanzia. Potrai conoscere gli elementi inclusi prima di procedere.'], 'Galleria', 'Esterno di uno chalet in legno, immagine illustrativa', 'Ingrandisci immagine', 'Chiudi immagine'),
 'rm': ('In chalet per la vita che Vus imaginai.', [
 'Chalet to Go sviluppa chalets da lain per differentas modas da viver e d’accoglier giasts. Il project cumenza cun l’utilisaziun: in agen dachasa, in refugi per la fin d’emna u ina unitad per in project d’alloschament.',
 'Da la tiny house cumpacta al chalet modular per famiglias u al project persunalisà: mintga model porscha in auter punct da partenza. Pensai a las persunas che dovran il spazi, als basegns dal mintgadi ed al lieu d’installaziun.',
 'Nossa equipa discuta cun Vus il model, la derivanza dal lain, ils detagls e las cundiziuns da garanzia. Uschia pudais Vus enconuscher las prestaziuns inclusas en l’offerta avant il proxim pass.'], 'Gallaria', 'Vista exteriura d’in chalet da lain, maletg illustrativ', 'Engrondir il maletg', 'Serrar il maletg'),
}
for _locale, _story in HOME_STORIES.items():
    CONTENT[_locale].update(zip(('story_title','story_paragraphs','gallery_label','exterior_alt','expand_image','close_image'),_story))
