"""Public buying information; no inferred specifications or delivery promises."""
from .content import CONTENT, PRODUCTS
import json
from pathlib import Path

# Independent editorial snapshot, maintained by the institutional site.
ABOUT = json.loads((Path(__file__).parent / 'about_content.json').read_text(encoding='utf-8'))

LABELS = {
 'pt-BR': ['Sobre a Chalet to Go','Perguntas frequentes sobre chalés','Chalés para hospedagem','Quanto custa um chalé?','Qual madeira é utilizada?','Como funcionam as garantias?','Como pedir uma proposta?','Compare os modelos','Modelo','Preço de referência','Próximos passos'],
 'pt-PT': ['Sobre a Chalet to Go','Perguntas frequentes sobre chalés','Chalés para alojamento','Quanto custa um chalé?','Qual a madeira utilizada?','Como funcionam as garantias?','Como pedir uma proposta?','Compare os modelos','Modelo','Preço de referência','Próximos passos'],
 'en': ['About Chalet to Go','Timber chalet questions and answers','Chalets for guest accommodation','How much does a chalet cost?','Which timber is used?','How do the warranties work?','How can I request a proposal?','Compare the models','Model','Reference price','Next steps'],
 'fr': ['À propos de Chalet to Go','Questions fréquentes sur les chalets','Chalets pour hébergement touristique','Combien coûte un chalet ?','Quel bois est utilisé ?','Quelles sont les garanties ?','Comment demander une offre ?','Comparer les modèles','Modèle','Prix de référence','Prochaines étapes'],
 'de': ['Über Chalet to Go','Häufige Fragen zu Holzchalets','Chalets für Gästeunterkünfte','Was kostet ein Chalet?','Welches Holz wird verwendet?','Welche Garantien gibt es?','Wie erhalte ich ein Angebot?','Modelle vergleichen','Modell','Richtpreis','Nächste Schritte'],
 'it': ['Informazioni su Chalet to Go','Domande frequenti sugli chalet','Chalet per strutture ricettive','Quanto costa uno chalet?','Quale legno viene utilizzato?','Come funzionano le garanzie?','Come richiedere una proposta?','Confronta i modelli','Modello','Prezzo indicativo','Prossimi passi'],
 'rm': ['Davart Chalet to Go','Dumondas frequentas davart chalets','Chalets per alloschar giasts','Quant custa in chalet?','Tge lain vegn duvrà?','Co funcziunan las garanzias?','Co poss jau dumandar ina offerta?','Cumparegliar ils models','Model','Pretsch indicativ','Proxims pass'],
}
STORIES = {
 'pt-BR': ['A Chalet to Go é uma empresa em fase inicial que desenvolve chalés de madeira e tiny houses. No Brasil, a implantação começa no bairro Minas Caixa, em Belo Horizonte, com uma equipe preparada para fabricar e vender a primeira unidade.', 'A proposta reúne três modelos: Basic, compacto e padronizado; Standard, modular para famílias ou turismo; e Premium, personalizado. Projetos Village são orçados individualmente e operações de exportação ou B2B dependem de contrato.', 'Para um projeto de hospedagem, comece pelo uso pretendido: quem será recebido, quantas unidades você deseja e onde serão instaladas. O modelo Standard é uma das opções da linha para essa finalidade.', 'Antes de definir a compra, alinhe a configuração, os itens incluídos e as condições de instalação na proposta. A viabilidade no terreno e as exigências locais precisam ser verificadas para cada projeto.', 'O valor do chalé não determina o retorno da hospedagem. Ocupação, diária, despesas de operação e investimento no terreno precisam compor uma análise própria; não há promessa de rentabilidade.'],
 'pt-PT': ['A Chalet to Go é uma empresa em fase inicial que desenvolve chalés de madeira e tiny houses. No Brasil, a implantação começa no bairro Minas Caixa, em Belo Horizonte, com uma equipa preparada para fabricar e vender a primeira unidade.', 'A proposta inclui três modelos: Basic, compacto e padronizado; Standard, modular para famílias ou turismo; e Premium, personalizado. Projetos Village têm orçamento individual e operações de exportação ou B2B dependem de contrato.', 'Num projeto de alojamento, comece pela utilização: quem pretende receber, quantas unidades deseja e onde serão instaladas. O modelo Standard é uma das opções para essa finalidade.', 'Antes da compra, defina a configuração, os elementos incluídos e as condições de instalação na proposta. A viabilidade no terreno e as exigências locais devem ser verificadas em cada projeto.', 'O preço do chalé não determina o retorno do alojamento. Ocupação, tarifa, despesas de exploração e investimento no terreno exigem uma análise própria; não há promessa de rentabilidade.'],
 'en': ['Chalet to Go is an early-stage company developing timber chalets and tiny houses. In Brazil, the operation starts in Minas Caixa, Belo Horizonte, with a team prepared to manufacture and sell the first unit.', 'The range comprises Basic, compact and standardised; Standard, modular for families or tourism; and Premium, customised. Village projects are quoted individually; export and B2B operations depend on a contract.', 'For an accommodation project, start with the intended use: who you will host, how many units you want and where they will be installed. Standard is one option in the range for this purpose.', 'Before purchasing, agree on the configuration, included items and installation terms in the proposal. Site feasibility and local requirements need to be checked for each project.', 'A chalet price does not determine accommodation returns. Occupancy, nightly rates, operating expenses and land investment require a separate assessment; profitability is not promised.'],
 'fr': ['Chalet to Go est une jeune entreprise qui développe des chalets en bois et des tiny houses. Au Brésil, l’implantation débute à Minas Caixa, Belo Horizonte, avec une équipe prête à fabriquer et vendre la première unité.', 'La gamme comprend Basic, compact et standardisé ; Standard, modulaire pour les familles ou le tourisme ; et Premium, personnalisé. Les projets Village sont sur devis et les opérations export ou B2B sont contractuelles.', 'Pour un projet d’hébergement, définissez les visiteurs, le nombre d’unités et le lieu d’installation. Standard est une des options de la gamme pour cet usage.', 'Avant l’achat, précisez la configuration, les éléments inclus et les conditions d’installation dans l’offre. La faisabilité sur le terrain et les exigences locales doivent être vérifiées pour chaque projet.', 'Le prix du chalet ne détermine pas le rendement de l’hébergement. Occupation, tarifs, dépenses et investissement foncier nécessitent une analyse distincte ; aucune rentabilité n’est promise.'],
 'de': ['Chalet to Go ist ein junges Unternehmen für Holzchalets und Tiny Houses. In Brasilien beginnt der Aufbau in Minas Caixa, Belo Horizonte, mit einem Team, das die erste Einheit herstellen und verkaufen kann.', 'Das Angebot umfasst Basic, kompakt und standardisiert; Standard, modular für Familien oder Tourismus; und Premium, individuell gestaltet. Village-Projekte werden einzeln kalkuliert; Export und B2B werden vertraglich vereinbart.', 'Planen Sie bei einer Gästeunterkunft zuerst Zielgruppe, Anzahl der Einheiten und Standort. Standard ist dafür eine Option innerhalb der Produktlinie.', 'Klären Sie vor dem Kauf Konfiguration, enthaltene Leistungen und Aufstellungsbedingungen im Angebot. Grundstückseignung und örtliche Anforderungen müssen je Projekt geprüft werden.', 'Der Chaletpreis bestimmt nicht die Rendite einer Unterkunft. Belegung, Übernachtungspreis, Betriebskosten und Grundstücksinvestition benötigen eine eigene Analyse; eine Rendite wird nicht zugesagt.'],
 'it': ['Chalet to Go è un’impresa in fase iniziale che sviluppa chalet in legno e tiny house. In Brasile, l’attività parte da Minas Caixa, Belo Horizonte, con un team preparato a fabbricare e vendere la prima unità.', 'La gamma comprende Basic, compatto e standardizzato; Standard, modulare per famiglie o turismo; e Premium, personalizzato. I progetti Village sono su preventivo; esportazione e B2B sono regolati da contratto.', 'Per un progetto ricettivo, definite ospiti, numero di unità e luogo di installazione. Standard è una delle opzioni della gamma per questo utilizzo.', 'Prima dell’acquisto, concordate configurazione, elementi inclusi e condizioni di installazione nella proposta. La fattibilità sul terreno e i requisiti locali vanno verificati per ogni progetto.', 'Il prezzo dello chalet non determina il rendimento dell’attività. Occupazione, tariffe, costi operativi e investimento nel terreno richiedono un’analisi distinta; non viene promessa redditività.'],
 'rm': ['Chalet to Go è ina interpresa en sia fasa iniziala che sviluppa chalets da lain e tiny houses. En Brasil cumenza l’activitad a Minas Caixa, Belo Horizonte, cun ina equipa preparada per fabritgar e vender l’emprima unitad.', 'La purschida cumpiglia Basic, cumpact e standardisà; Standard, modular per famiglias u turissem; e Premium, persunalisà. Projects Village survegnan offertas individualas; export e B2B dependan d’in contract.', 'Per in project d’alloschament, defini Voss giasts, il dumber d’unitads ed il lieu d’installaziun. Standard è ina da las opziuns per quest diever.', 'Avant la cumpra, sclerì la configuraziun, las prestaziuns inclusas e las cundiziuns d’installaziun en l’offerta. Il terren e las pretensiuns localas ston vegnir examinads per mintga project.', 'Il pretsch dal chalet na determinescha betg il retgav da l’alloschament. Occupaziun, pretschs, custs da gestiun ed investiziun en il terren dovran in’atgna analisa; nagina rentabilitad vegn empermessa.'],
}
PAGES = {'sobre':0, 'perguntas-frequentes':1, 'chales-para-hospedagem':2}

def resources(locale):
    labels = LABELS[locale]
    return [{'slug':slug,'title':labels[index]} for slug,index in PAGES.items()]

def page_content(slug, locale):
    text, labels, story = CONTENT[locale], LABELS[locale], STORIES[locale]
    return {'slug':slug,'title':labels[PAGES[slug]], 'labels':labels, 'chapters': ABOUT[locale] if slug=='sobre' else [],
            'intro':story[0] if slug=='sobre' else text['collection_intro'] if slug=='perguntas-frequentes' else story[2],
            'paragraphs':story[:2] if slug=='sobre' else story[2:] if slug=='chales-para-hospedagem' else [],
            'questions':[(labels[3], text['price_note']), (labels[4],text['material_body']),
                         (labels[5],text['swiss_body']+' '+text['brazil_body']), (labels[6],text['closing_body'])]}
