"""Interface translations; personal copy can be supplied in each card JSON."""
KEYS = ('connect', 'whatsapp', 'save', 'share', 'phone', 'email', 'site', 'site_sub', 'instagram_sub', 'linkedin_sub', 'maps', 'home', 'contact', 'description', 'copied', 'copy_help', 'copy_label', 'footer', 'language', 'automatic', 'apply')
ROWS = {
    'pt-BR': ('Vamos nos conectar', 'Conversar no WhatsApp', 'Salvar contato', 'Compartilhar cartão', 'Telefone', 'E-mail', 'Conheça a Chalet to Go', 'Nosso site', 'Acompanhe nossas histórias', 'Vamos nos conectar', 'Abrir no mapa', 'Página inicial', 'Contato e redes sociais', 'Salve o contato e conecte-se.', 'Link copiado. Pronto para compartilhar!', 'Selecione e copie o link abaixo.', 'Copie o link do cartão:', 'Natureza em cada detalhe', 'Idioma', 'Automático', 'Aplicar'),
    'pt-PT': ('Vamos estabelecer contacto', 'Conversar no WhatsApp', 'Guardar contacto', 'Partilhar cartão', 'Telefone', 'E-mail', 'Conheça a Chalet to Go', 'O nosso site', 'Acompanhe as nossas histórias', 'Vamos estabelecer contacto', 'Abrir no mapa', 'Página inicial', 'Contacto e redes sociais', 'Guarde o contacto e entre em contacto.', 'Ligação copiada. Pronta para partilhar!', 'Selecione e copie a ligação abaixo.', 'Copie a ligação do cartão:', 'Natureza em cada detalhe', 'Idioma', 'Automático', 'Aplicar'),
    'en': ("Let’s connect", 'Chat on WhatsApp', 'Save contact', 'Share card', 'Phone', 'Email', 'Discover Chalet to Go', 'Our website', 'Follow our stories', "Let’s connect", 'Open in maps', 'Home', 'Contact and social networks', 'Save the contact and get in touch.', 'Link copied. Ready to share!', 'Select and copy the link below.', 'Copy the card link:', 'Nature in every detail', 'Language', 'Automatic', 'Apply'),
    'de': ('Vernetzen wir uns', 'Auf WhatsApp schreiben', 'Kontakt speichern', 'Visitenkarte teilen', 'Telefon', 'E-Mail', 'Chalet to Go entdecken', 'Unsere Website', 'Unsere Geschichten verfolgen', 'Vernetzen wir uns', 'In Karten öffnen', 'Startseite', 'Kontakt und soziale Netzwerke', 'Kontakt speichern und in Verbindung bleiben.', 'Link kopiert. Bereit zum Teilen!', 'Den Link unten auswählen und kopieren.', 'Link zur Visitenkarte kopieren:', 'Natur in jedem Detail', 'Sprache', 'Automatisch', 'Anwenden'),
    'fr': ('Restons en contact', 'Discuter sur WhatsApp', 'Enregistrer le contact', 'Partager la carte', 'Téléphone', 'E-mail', 'Découvrez Chalet to Go', 'Notre site', 'Suivez nos histoires', 'Restons en contact', 'Ouvrir dans les cartes', 'Accueil', 'Contact et réseaux sociaux', 'Enregistrez le contact et échangeons.', 'Lien copié. Prêt à partager !', 'Sélectionnez et copiez le lien ci-dessous.', 'Copiez le lien de la carte :', 'La nature dans chaque détail', 'Langue', 'Automatique', 'Appliquer'),
    'it': ('Restiamo in contatto', 'Scrivi su WhatsApp', 'Salva contatto', 'Condividi biglietto', 'Telefono', 'E-mail', 'Scopri Chalet to Go', 'Il nostro sito', 'Segui le nostre storie', 'Restiamo in contatto', 'Apri nelle mappe', 'Pagina iniziale', 'Contatti e social network', 'Salva il contatto e restiamo in contatto.', 'Link copiato. Pronto da condividere!', 'Seleziona e copia il link qui sotto.', 'Copia il link del biglietto:', 'Natura in ogni dettaglio', 'Lingua', 'Automatico', 'Applica'),
    'rm': ('Restain en contact', 'Scriver sin WhatsApp', 'Memorisar il contact', 'Cundivider la carta', 'Telefon', 'E-mail', 'Scuvri Chalet to Go', 'Nossa pagina web', 'Suandai nossas istorgias', 'Restain en contact', 'Avrir en las chartas', 'Pagina iniziala', 'Contact e raits socialas', 'Memorisai il contact e restain en contact.', 'Colliaziun copiada!', 'Tscherna e copiescha la colliaziun sutvart.', 'Copiar la colliaziun da la carta:', 'Natira en mintga detagl', 'Lingua', 'Automatic', 'Applitgar'),
}
CATALOGS = {locale: dict(zip(KEYS, values, strict=True)) for locale, values in ROWS.items()}
